apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels: 
    app: fastapi  # Corrected label format
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi  # Label selector to match the labels in template
  template:
    metadata:
      labels:
        app: fastapi  # Labels for the pod template
    spec:
      containers:
        - name: legal
          image: "otaviocosta2110/fastpython:latest"
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels: 
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: "postgres:latest"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials

