apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels: 
    app: fastapi  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi 
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: legal
          image: "otaviocosta2110/fastpython:latest"
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: postgres-credentials
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels: 
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: "postgres:latest"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
          command: ["bash", "-c", "psql -U ${POSTGRES_USER} -c 'CREATE TABLE IF NOT EXISTS users (id serial PRIMARY KEY, name varchar(255), email varchar(255), password varchar(255));'"]
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
