services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/python/app/
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
